# docker-compose.yml
version: '3.8'

services:
  hub-postgres:
    image: postgres:15
    container_name: hub-postgres
    ports:
      - '5434:5432' # 前面是宿主机端口，根据自己情况修改
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - hub-django-postgres-network
  hub-api:
    # build: .
    image: ghcr.io/worshipmoon/hubheweishi:v1.0 # ghcr
    container_name: hub-api
    ports:
      - '8000:8000'
    volumes:
      # - .:/app
      - ./gunicorn.conf.py:/app/gunicorn.conf.py  # 挂载 gunicorn 配置文件到容器
      - ./logs:/app/logs  # 挂载日志目录到宿主机
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    command: sh -c "python manage.py migrate && gunicorn --config gunicorn.conf.py project.wsgi:application"
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  
    depends_on:
      # - hub-postgres
      hub-postgres:
        condition: service_healthy
    restart: always
    networks:
      - hub-django-postgres-network
  hub-zfbvn:
    image: docker pull ghcr.io/worshipmoon/zfbvn:v1.0 # ghcr
    container_name: hub-zfbvn
    ports:
      - '4173:4173'
    volumes:
      - ./.env:/app/.env
    command: sh -c "npm run preview"
    restart: always
    networks:
      - hub-django-postgres-network

volumes:
  pg_data:
  logs:  # 定义一个日志卷
networks:
  hub-django-postgres-network:
