name: hub.heweishi.image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "image/**"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      