# Generated by Django 5.0.6 on 2024-11-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0002_vpnlinks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VpnLink",
        ),
    ]
