# Generated by Django 5.0.6 on 2024-11-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0004_vpnlink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VpnLinks",
        ),
    ]
