# Generated by Django 5.0.6 on 2024-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0006_alter_vpnlink_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnlink",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
