# Generated by Django 5.0.6 on 2024-11-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0007_alter_vpnlink_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="VpnZfbOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_id", models.IntegerField(help_text="对应的价格Id")),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="备注", max_length=255, null=True
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                ("month", models.IntegerField(help_text="多少个月")),
                ("device", models.IntegerField(help_text="设备数量做记录")),
                ("code", models.CharField(help_text="每个人的码", max_length=255)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未激活"), (1, "激活"), (2, "已过期")],
                        default=0,
                        help_text="状态",
                    ),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(
                        blank=True, help_text="到期时间(激活的时候写入)", null=True
                    ),
                ),
                ("pay", models.IntegerField(help_text="需要支付的费用")),
                ("level", models.IntegerField()),
                ("pay_code", models.CharField(help_text="红包口令", max_length=255)),
                ("email", models.CharField(max_length=255)),
                (
                    "pay_status",
                    models.SmallIntegerField(
                        choices=[(0, "未结"), (1, "已结")],
                        default=2,
                        help_text="代理的单是否结算",
                    ),
                ),
                ("ctCode", models.CharField(blank=True, max_length=255, null=True)),
                ("ctStatus", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="vpnlink",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, help_text="状态"
            ),
        ),
    ]
