# Generated by Django 5.0.6 on 2024-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0008_vpnzfborder_alter_vpnlink_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnzfborder",
            name="pay_status",
            field=models.SmallIntegerField(
                choices=[(0, "未结"), (1, "已结")],
                default=0,
                help_text="代理的单是否结算",
            ),
        ),
    ]
