# Generated by Django 5.0.6 on 2024-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0010_rename_ctcode_vpnzfborder_ct_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VpnZfbPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="商品名称"
                    ),
                ),
                (
                    "month",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="月份"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="链接"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "device",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="设备数量"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="金额")),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="1 启用 0禁用"),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="到期时间"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        default=1,
                        verbose_name="用户等级\r\n不同的用户等级用不同的节点配置\r\n1用最好的\r\n2一般的\r\n3最一般的",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="vpnzfborder",
            name="code",
            field=models.CharField(help_text="每个人的码", max_length=255, unique=True),
        ),
    ]
