# Generated by Django 5.0.6 on 2024-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0014_vpnzfbprice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnzfborder",
            name="ct_status",
            field=models.SmallIntegerField(
                default=0, help_text="代理的单是否结算 1已结 0 未结"
            ),
        ),
        migrations.AlterField(
            model_name="vpnzfborder",
            name="pay_status",
            field=models.SmallIntegerField(
                choices=[(0, "未收款"), (1, "已收")], default=0, help_text="收款状态"
            ),
        ),
    ]
