# Generated by Django 5.0.6 on 2024-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0016_alter_vpnlink_code_alter_vpnlink_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnlink",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
