# Generated by Django 5.0.6 on 2024-12-04 13:35

import vnbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnbase", "0017_alter_vpnlink_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnlink",
            name="code",
            field=models.CharField(
                default=vnbase.models.VpnLink.generate_code,
                help_text="每个链接的码",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vpnzfborder",
            name="code",
            field=models.CharField(
                help_text="每个链接的码", max_length=50, unique=True
            ),
        ),
    ]
